version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '18.1.0'
      - run:
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
          name: Setting up pnpm
      - run:
          command: pnpm install --frozen-lockfile
          name: Installing dependencies
      - run:
          command: pnpm lint
          name: Running tests
      - run:
          command: pnpm test
          name: Running tests
workflows:
  test:
    jobs:
      - test
